<a href="https://colab.research.google.com/github/Yuta-Toramoto/remote/blob/main/practice_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

■方針
①input1, input2を読み込む。②それぞれ重複を削除する③inut2における１４式竹筒銃についてcategoryの甲をitem_nameに追記したのちに削除、それぞれ左に詰める
④input1, input2を結合する
⑤unit*meanの値を用いて新たにsales列を作成する。

In [1]:
import pandas as pd
import numpy as np
from google.colab import files

In [13]:
##input1のcsvをインポート
uploaded = files.upload()

Saving input1.csv to input1 (1).csv
Saving input2.csv to input2 (3).csv

In [19]:
import io

input1 = pd.read_csv(io.BytesIO(uploaded['input1.csv']))
input1

          ymd  item_code  item_name category  unit  mean
0  2022/12/12          1   わかばシューター    シューター    10   123
1  2022/12/12          1   わかばシューター    シューター    10   123
2  2022/12/13          2   スプラシューター    シューター    12   100
3  2022/12/14          3    スプラローラー     ローラー    14   150
4  2022/12/15          4  スプラマニューバー   マニューバー     5   100
5  2022/12/15          5  デュアルスイーパー   マニューバー     5   100

列名に空白があったため名前指定してdfを作成。その後１行目（元のheaderを削除した）

In [26]:
input2_pre = pd.read_csv(io.BytesIO(uploaded['input2.csv']), names = ("ymd", "item_code", "item_name", "category", "unit", "mean", "dummy"))
input2 = input2_pre.drop(0, axis=0)
input2

          ymd item_code    item_name category    unit mean  dummy
1  2022/12/12      0006    スプラチャージャー   チャージャー      10  123    NaN
2  2022/12/13      0007  スクイックリンアルファ   チャージャー      12  100    NaN
3  2022/12/14      0008       14式竹筒銃        甲  チャージャー   14  150.0
4  2022/12/15      0009   バケットスロッシャー   スロッシャー       5  100    NaN
5  2022/12/15      0010         ヒッセン   スロッシャー       5  100    NaN

それぞれ重複を削除

In [27]:
input1_dd = input1[~input1.duplicated()]
input1_dd

          ymd  item_code  item_name category  unit  mean
0  2022/12/12          1   わかばシューター    シューター    10   123
2  2022/12/13          2   スプラシューター    シューター    12   100
3  2022/12/14          3    スプラローラー     ローラー    14   150
4  2022/12/15          4  スプラマニューバー   マニューバー     5   100
5  2022/12/15          5  デュアルスイーパー   マニューバー     5   100

In [66]:
input2_dd = input2[~input2.duplicated()]
input2_dd

          ymd item_code    item_name category    unit mean  dummy
1  2022/12/12      0006    スプラチャージャー   チャージャー      10  123    NaN
2  2022/12/13      0007  スクイックリンアルファ   チャージャー      12  100    NaN
3  2022/12/14      0008       14式竹筒銃        甲  チャージャー   14  150.0
4  2022/12/15      0009   バケットスロッシャー   スロッシャー       5  100    NaN
5  2022/12/15      0010         ヒッセン   スロッシャー       5  100    NaN

*③inut2における１４式竹筒銃についてcategoryの甲をitem_nameに追記したのちに削除、それぞれ左に詰める*

In [67]:
##input2_ddから編集したい行を抽出
input2_edit1 = input2_dd[2:3]
input2_edit1

          ymd item_code item_name category    unit mean  dummy
3  2022/12/14      0008    14式竹筒銃        甲  チャージャー   14  150.0

In [64]:
# input2_edit1.loc[3, "item_name"] = "14式竹筒銃甲"
# input2_edit1.loc[3, "category"] = "チャージャー"
# input2_edit1.loc[3, "unit"] = 14
# input2_edit1.loc[3, "mean"] = 150.0
# input2_edit1.loc[3, "dummy"] = np.NaN
# input2_edit1

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

          ymd item_code item_name category unit   mean  dummy
3  2022/12/14      0008   14式竹筒銃甲   チャージャー   14  150.0    NaN

In [70]:
edit = ["2022/12/14, 0008", "14式竹筒銃甲", "チャージャー", 14, 150.0, np.NaN]

for i in range(1, len(edit)+1):
  input2_edit1.iat[3, i] = edit[i]

input2_edit1

IndexError: ignored